#!/usr/bin/env bash

domain=$1
subdomain=$2

function display_info {
    local sub=$1
    local record_type=$(dig $sub.$domain +short | awk 'NR==1 {print $2}')
    local destination=$(dig $sub.$domain +short | awk 'NR==1 {print $1}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
}

if [ -z "$subdomain" ]; then
    display_info www
    display_info lb-01
    display_info web-01
    display_info web-02
else
    display_info $subdomain
fi
