#!/bin/bash

domain=$1
subdomain=$2

function audit_subdomain {
    sub=$1
    record=$(dig "$sub.$domain" +short)
    type=$(dig "$sub.$domain" +short | awk '{print $2}')
    echo "The subdomain $sub is a $type record and points to $record"
}

if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    audit_subdomain "$sub"
done
