#!/usr/bin/env bash

# Configure ufw to forward incoming traffic from port 8080/TCP to port 80/TCP

# Set the default forward policy to ACCEPT
sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw

# Set the default input/output policies to DROP
sed -i 's/DEFAULT_INPUT_POLICY="ACCEPT"/DEFAULT_INPUT_POLICY="DROP"/g' /etc/default/ufw
sed -i 's/DEFAULT_OUTPUT_POLICY="ACCEPT"/DEFAULT_OUTPUT_POLICY="DROP"/g' /etc/default/ufw

# Add a rule to redirect incoming traffic from port 8080/TCP to port 80/TCP
sed -i '1 i\-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80' /etc/ufw/before.rules

# Reload the ufw firewall
ufw reload
