#!/usr/bin/env bash

# Configure SSH to allow port forwarding
sudo sed -i '/^#.*GatewayPorts/ s/^#//' /etc/ssh/sshd_config
sudo sed -i '/^#.*AllowTcpForwarding/ s/^#//' /etc/ssh/sshd_config
sudo systemctl reload ssh

# Allow incoming traffic on the port to be forwarded
sudo ufw allow 8080/tcp

# Display forwarding rules
echo "Forwarding from port 8080 to port 80 on web-01"
echo "External IP: $(curl -s icanhazip.com)"
echo "Internal IP: $(hostname -I | awk '{print $1}')"

# Note: The router or firewall must also be configured to forward traffic on port 8080 to web-01
